Repository sociomantic-tsunami/dmxnet, pull requests merged in 2018-11, with the labels that each got.

#89 Add closure allocation check to CI stages
  .travis.yml
  ci/closures.sh
Labels: d2, type-test

#91 Replace all version (UnitTest) with version (unittest)
  integrationtest/mxnet/main.d
  src/mxnet/API.d
  src/mxnet/Atomic.d
  src/mxnet/Context.d
  src/mxnet/Exception.d
  src/mxnet/Executor.d
  src/mxnet/Handle.d
  src/mxnet/NDArray.d
  src/mxnet/Symbol.d
  src/mxnet/Util.d
Labels: d2, type-cleanup

#92 Replace all uses of Immut!(...) with immutable(...)
  src/mxnet/NDArray.d
  src/mxnet/Symbol.d
Labels: d2, type-cleanup

#94 Replace all uses of enableStomping with assumeSafeAppend
  src/mxnet/Symbol.d
Labels: d2, type-cleanup

#95 Replace all uses of min_normal!(T) with T.min_normal
  src/mxnet/Util.d
Labels: d2, type-cleanup

#96 Remove or replace all imports of ocean.transition
  integrationtest/mxnet/MNIST.d
  integrationtest/mxnet/main.d
  src/mxnet/API.d
  src/mxnet/Atomic.d
  src/mxnet/Exception.d
  src/mxnet/Executor.d
  src/mxnet/Handle.d
  src/mxnet/NDArray.d
  src/mxnet/Symbol.d
  src/mxnet/Util.d
  src/mxnet/c/c_api.d
Labels: d2, type-cleanup

#97 Encapsulate imports required for debugReport helper function
  src/mxnet/Handle.d
Labels: d2, type-cleanup

#98 Add a .keep file for the relnotes folder
  relnotes/.keep
Labels: type-ci

#100 Use enum for manifest constants
  src/mxnet/NDArray.d
  src/mxnet/Util.d
Labels: d2, type-cleanup
