Repository sociomantic-tsunami/dmxnet, pull requests merged in 2018-06, with the labels that each got.

#62 Enable automatic update PRs for minor versions except ocean
  .neptune.yml
Labels: type-ci

#65 Fix MXNET_ENGINE_TYPE settings for Travis CI
  .travis.yml
Labels: type-bug, type-ci

#64 Export MXNET_ENGINE_TYPE from Config.mak if not already set
  Config.mak
Labels: type-ci

#70 Add support for auto-converted D2 releases
  .travis.yml
Labels: type-ci

#72 Shutdown MXNet engine after running unittests
  src/mxnet/API.d
Labels: type-bug, type-enhancement

#75 Simplify docker image build script
  docker/build
Labels: type-ci, type-cleanup

#76 Ensure MNIST usage example does not require loading the dataset
  integrationtest/mxnet/MNIST.d
Labels: type-bug, type-test

#78 Update copyright notice to dunnhumby Germany GmbH
  integrationtest/mxnet/MNIST.d
  integrationtest/mxnet/main.d
  src/mxnet/API.d
  src/mxnet/Atomic.d
  src/mxnet/Context.d
  src/mxnet/Exception.d
  src/mxnet/Executor.d
  src/mxnet/Handle.d
  src/mxnet/MXNet.d
  src/mxnet/NDArray.d
  src/mxnet/Symbol.d
  src/mxnet/Util.d
Labels: type-doc
